# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
repos:
  CRAN: https://cloud.r-project.org
  PIK:  https://rse.pik-potsdam.de/r/packages/
cache: packages
latex: false
pandoc: false
sudo: false
r_packages: lucode
install:
  - Rscript -e "for(pkg in c('devtools','testthat')) if(!requireNamespace(pkg)) install.packages(pkg)"
  - Rscript -e "if(!requireNamespace('lucode')) devtools::install_github('pik-piam/lucode')"
script:
  - Rscript -e "null <- lucode::codeCheck(strict=TRUE)"

